spring:
  application:
    name:  eshop-product
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.106:3306/transaction?useUnicode=true&characterEncoding=UTF-8

  rabbitmq:
    addresses: 192.168.1.102:5672
    ####连接地址

    ####账号
    username: rabbitadmin
    ####密码
    password: 123456
    ### 地址
    virtual-host: /eshop
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 1000
        ####开启手动ack
        acknowledge-mode: manual

        default-requeue-rejected: false